# Site settings
title:       Liberty
tagline:     Basic example of a Jekyll site with Sass enabled.
email:       jcomes@highereducation.com
baseurl:    "" # the subpath of your site, e.g. /blog
url:        "" # the base hostname & protocol for your site, e.g. http://example.com

# Assets
sass:
    sass_dir:  _scss
    # style:     compressed


gems:
  - jekyll-inline-svg


svg:
  optimize: true