# Site settings
title:      Liberty University
tagline:    Take the first step toward your future with one of our many 100% online programs of study.
email:      jcomes@highereducation.com
baseurl:    "" # the subpath of your site, e.g. /blog
url:        "" # the base hostname & protocol for your site, e.g. http://example.com

# Assets
sass:
    sass_dir:  _scss
    # style:     compressed


gems:
  - jekyll-inline-svg


svg:
  optimize: true