# Site settings
title:       Liberty
tagline:     Basic example of a Jekyll site with Sass enabled.
email:       jcomes@highereducation.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:    "" # the subpath of your site, e.g. /blog
url:        "" # the base hostname & protocol for your site, e.g. http://example.com
privacy:    >- # <h3>Privacy Policy</h3><p>This is a summary of Liberty University’s Privacy Policy. You may view the full privacy policy here.</p><h3>Policy Statement</h3><p>Liberty University monitors and collects various types of information from our website visitors for legal and policy compliance, for the maintenance and security of the network, and so we can adjust our websites to meet our users’ needs and expectations. Some of this information is collected automatically and other information is provided by site users. The university reserves the right to restrict the use of its information technology resources and to remove or limit access to information technology resources.</p><h3>Information Collected Automatically</h3><p>The University collects limited, non-personal identifying information your browser makes available when visiting websites. We may aggregate this non-identifying information for reporting purposes to assess the effectiveness of our websites without disclosing specific information that would link to any individual. This includes:</p><ul><li>Your Internet Protocol Address</li><li>The Browser type (Internet Explorer, Firefox, etc.)</li><li>Your computer’s operating system (Windows, Macintosh, etc.)</li><li>Your Internet domain (AOL, EarthLink, etc.)</li></ul>

# Assets
sass:
    sass_dir:  _scss
    # style:     compressed


gems:
  - jekyll-inline-svg


svg:
  optimize: true